### ISSUE TITLE
Installation instructions lead to an error

### ISSUE THREAD

**Issue by nukularrr** [mit-ll-responsible-ai/equine-webapp#13]
The `npm start` step produces an error, but things do work in dev mode using `npm run dev`. 

Error is:
```
[Error: ENOENT: no such file or directory, open '/<path>/equine-webapp/client/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/<path>/equine-webapp/client/.next/BUILD_ID'
}
```
where `<path>` is the path to the cloned git repo.

**Comment by harryli0088** [comment]
Fixed in https://github.com/mit-ll-responsible-ai/equine-webapp/pull/16
